### ISSUE TITLE
Cannot reproduce the claimed SHARK inference number on a A100-SXM4-40GB GPU

### ISSUE THREAD

**Issue by swb1234554321** [nod-ai/SHARK-Runtime#1]
**Describe the bug**
I have tried the 'PerformanceDevBranch' and 'PerformanceStageBranch' on A100 with the benchmark script provided here: https://github.com/powderluv/transformer-benchmarks. 
The best score we got with FP32 for SHARK is around 2.9 ms, which is slower than the 2.8 ms for onnxruntime. (BERT microsoft/MiniLM-L12-H384-uncased)

Also, does SHARK support FP16/INT8 inference?

**To Reproduce**
Just build from source and run the benchmark script.

**Comment by powderluv** [comment]
Please try it on https://github.com/NodLabs/SHARK/tree/PerfDevMarch2022 branch. We just verified it to be 2.09ms from the benchmark module and 2.15ms from Python.  Please reopen if you have any issues.

**Comment by swb1234554321** [comment]
Thanks for the response. This branch works :).
