### ISSUE TITLE
Using the Shark Runtime for M1 Pro?

### ISSUE THREAD

**Issue by kaysagit** [nod-ai/SHARK-Runtime#3]
Hi,

I read the article about the benchmark of the M1 Max. Does the Shark Runtime also work for the M1 Pro and allows to train pytorch models like the YOLOv5 or only for inference?

Thank you very much!

**Comment by powderluv** [comment]
Yes it works on all M1 GPUs and works for both training and inference. We haven't tested Yolov5 but please do let us know if there are any ops missing.

**Comment by mrdvince** [comment]
@powderluv 
Looking to try running it but can't seem to see any guide on how to get shark setup on M1. is there such a guide and using PyTorch on/with it.

Is there such a getting started guide? or I'm probably missing something.
Thanks

**Comment by tcapelle** [comment]
Do you have a tutorial/readme on how to install dependencies an use tensorflow/pytorch with Shark?

**Comment by lowfuel** [comment]
> Do you have a tutorial/readme on how to install dependencies an use tensorflow/pytorch with Shark?

Would love some instructions, too.

**Comment by mrdvince** [comment]
Been trying this with PyTorch and I quite can't seem to figure out how the PyTorch models were/can be trained on the M1 GPU

**Comment by powderluv** [comment]
I plan to publish new binaries and a easy to use instructions in a few days. Stay tuned.

**Comment by powderluv** [comment]
The documentation will likely be in the dshark repo and tracked with this issue https://github.com/NodLabs/dSHARK/issues/26 

The APIs should work already if you can build from source and export your PYTHONPATH.

**Comment by powderluv** [comment]
Please check dSHARK apis. It should work out the box. https://github.com/NodLabs/dSHARK
